data:
  batch_size: 24
  color_jitter_strength: 0.0
  crop_scale:
  - 0.3
  - 1.0
  crop_size: 224
  image_folder: imagenet-mini/
  num_workers: 0
  pin_mem: true
  root_path: /home/sboughanem/ssl/cs2952x/ijepa/zdata
  use_color_distortion: false
  use_gaussian_blur: false
  use_horizontal_flip: false
logging:
  folder: /home/sboughanem/ssl/cs2952x/ijepa/logs/vitt16.224-bs.24-ep.300/
  write_tag: jepa
mask:
  allow_overlap: false
  aspect_ratio:
  - 0.75
  - 1.5
  enc_mask_scale:
  - 0.85
  - 1.0
  min_keep: 10
  num_enc_masks: 1
  num_pred_masks: 4
  patch_size: 14
  pred_mask_scale:
  - 0.15
  - 0.2
meta:
  copy_data: false
  load_checkpoint: false
  model_name: vit_tiny
  pred_depth: 6
  pred_emb_dim: 192
  read_checkpoint: null
  use_bfloat16: true
optimization:
  enable_vicreg: true
  ema:
  - 0.996
  - 1.0
  epochs: 300
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.001
  start_lr: 0.0002
  warmup: 40
  weight_decay: 0.04
